-- MySQL Script generated by MySQL Workbench
-- 07/11/16 19:40:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_cronos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cronos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cronos` DEFAULT CHARACTER SET utf8 ;
USE `db_cronos` ;

-- -----------------------------------------------------
-- Table `db_cronos`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`funcionario` (
  `id_funcionario` SMALLINT NOT NULL AUTO_INCREMENT,
  `nome_funcionario` VARCHAR(50) NOT NULL,
  `matricula_funcionario` VARCHAR(11) NULL,
  `cpf_funcionario` VARCHAR(11) NULL,
  `email_funcionario` VARCHAR(50) NOT NULL,
  `telefone_funcionario` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_cronos`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`periodo` (
  `id_periodo` TINYINT NOT NULL AUTO_INCREMENT,
  `nome_periodo` VARCHAR(30) NOT NULL,
  `descricao_periodo` VARCHAR(50) NOT NULL,
  `data_inicio_periodo` DATE NOT NULL,
  `data_termino_periodo` DATE NOT NULL,
  `is_periodo_letivo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_periodo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_cronos`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`agendamento` (
  `id_agendamento` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `motivo` VARCHAR(50) NOT NULL,
  `id_funcionario` SMALLINT NOT NULL,
  `id_periodo` TINYINT NOT NULL,
  PRIMARY KEY (`id_agendamento`),
  INDEX `fk_agendamento_funcionario1_idx` (`id_funcionario` ASC),
  INDEX `fk_agendamento_periodo1_idx` (`id_periodo` ASC),
  CONSTRAINT `fk_agendamento_funcionario1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `db_cronos`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamento_periodo1`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `db_cronos`.`periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_cronos`.`perfil_sala_turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`perfil_sala_turma` (
  `id_perfil_sala_turma` TINYINT NOT NULL AUTO_INCREMENT,
  `nome_perfil_sala_turma` VARCHAR(50) NOT NULL,
  `descricao_perfil_sala_turma` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_perfil_sala_turma`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_cronos`.`predio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`predio` (
  `id_predio` TINYINT NOT NULL AUTO_INCREMENT,
  `nome_predio` VARCHAR(50) NOT NULL,
  `descricao_predio` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_predio`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_cronos`.`sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`sala` (
  `id_sala` SMALLINT NOT NULL AUTO_INCREMENT,
  `nome_sala` VARCHAR(50) NOT NULL,
  `descricao_sala` VARCHAR(100) NOT NULL,
  `capacidade_sala` SMALLINT NOT NULL,
  `tipo_quadro_sala` VARCHAR(30) NOT NULL,
  `utilizar_distribuicao` TINYINT(1) NOT NULL DEFAULT 1,
  `utilizar_agendamento` TINYINT(1) NOT NULL DEFAULT 1,
  `distribuir` TINYINT(1) NOT NULL DEFAULT 1,
  `id_perfil` TINYINT NOT NULL,
  `id_predio` TINYINT NOT NULL,
  PRIMARY KEY (`id_sala`),
  INDEX `fk_sala_tipo1_idx` (`id_perfil` ASC),
  INDEX `fk_sala_predio1_idx` (`id_predio` ASC),
  CONSTRAINT `fk_sala_tipo1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `db_cronos`.`perfil_sala_turma` (`id_perfil_sala_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sala_predio1`
    FOREIGN KEY (`id_predio`)
    REFERENCES `db_cronos`.`predio` (`id_predio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 88
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_cronos`.`chave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`chave` (
  `id_chave` SMALLINT NOT NULL AUTO_INCREMENT,
  `codigo_chave` VARCHAR(20) NOT NULL,
  `id_sala` SMALLINT NOT NULL,
  PRIMARY KEY (`id_chave`),
  UNIQUE INDEX `codigo_chave_UNIQUE` (`codigo_chave` ASC),
  INDEX `fk_chave_sala1_idx` (`id_sala` ASC),
  CONSTRAINT `fk_chave_sala1`
    FOREIGN KEY (`id_sala`)
    REFERENCES `db_cronos`.`sala` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_cronos`.`operacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`operacao` (
  `id_operacao` SMALLINT NOT NULL AUTO_INCREMENT,
  `nome_operacao` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_operacao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_cronos`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`usuario` (
  `id_usuario` SMALLINT NOT NULL AUTO_INCREMENT,
  `login_usuario` VARCHAR(20) NOT NULL,
  `senha_usuario` VARCHAR(200) NOT NULL,
  `ativo_usuario` TINYINT(1) NOT NULL DEFAULT '1',
  `tentativas_login_usuario` SMALLINT(6) NOT NULL DEFAULT '0',
  `id_funcionario` SMALLINT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_funcionario1_idx` (`id_funcionario` ASC),
  CONSTRAINT `fk_usuario_funcionario1`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `db_cronos`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_cronos`.`historico_chave`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`historico_chave` (
  `id_historico_chave` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `hora_realizacao_operacao` DATETIME NOT NULL,
  `id_chave` SMALLINT NOT NULL,
  `id_operacao` SMALLINT NOT NULL,
  `id_usuario` SMALLINT NULL,
  PRIMARY KEY (`id_historico_chave`),
  INDEX `fk_historico_chave_chave1_idx` (`id_chave` ASC),
  INDEX `fk_historico_chave_operacao1_idx` (`id_operacao` ASC),
  INDEX `fk_historico_chave_usuario1_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_historico_chave_chave1`
    FOREIGN KEY (`id_chave`)
    REFERENCES `db_cronos`.`chave` (`id_chave`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_chave_operacao1`
    FOREIGN KEY (`id_operacao`)
    REFERENCES `db_cronos`.`operacao` (`id_operacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historico_chave_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_cronos`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_cronos`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`horario` (
  `id_horario` SMALLINT NOT NULL AUTO_INCREMENT,
  `horario` TINYINT NOT NULL,
  `inicio_horario` TIME NOT NULL,
  `termino_horario` TIME NOT NULL,
  `horario_intermediario` TIME NOT NULL,
  `turno` CHAR(1) NOT NULL,
  `inicio_horario_absoluto` TIME NOT NULL,
  `termino_horario_absoluto` TIME NOT NULL,
  PRIMARY KEY (`id_horario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_cronos`.`papel_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`papel_usuario` (
  `id_papel` TINYINT NOT NULL AUTO_INCREMENT,
  `nome_papel` VARCHAR(40) NOT NULL,
  `descricao_papel` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_papel`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_cronos`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`departamento` (
  `id_departamento` TINYINT NOT NULL,
  `nome_departamento` VARCHAR(70) NOT NULL,
  `descricao_departamento` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cronos`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`turma` (
  `id_turma` SMALLINT NOT NULL AUTO_INCREMENT,
  `codigo_componente_turma` VARCHAR(20) NOT NULL,
  `nome_componente_turma` VARCHAR(90) NOT NULL,
  `nome_docente_turma` VARCHAR(80) NOT NULL,
  `horario_turma` VARCHAR(30) NOT NULL,
  `capacidade_turma` SMALLINT(6) NOT NULL,
  `numero_turma` TINYINT NOT NULL,
  `alunos_matriculados_turma` SMALLINT(6) NOT NULL DEFAULT 0,
  `distribuir` TINYINT(1) NOT NULL DEFAULT '1',
  `local` VARCHAR(30) NOT NULL DEFAULT 'INDEFINIDO',
  `id_perfil` TINYINT NOT NULL,
  `id_predio` TINYINT NOT NULL DEFAULT 1,
  `id_periodo` TINYINT NOT NULL,
  `id_departamento` TINYINT NOT NULL,
  `id_sala_temp` SMALLINT NULL,
  PRIMARY KEY (`id_turma`),
  INDEX `fk_turma_tipo1_idx` (`id_perfil` ASC),
  INDEX `fk_turma_predio1_idx` (`id_predio` ASC),
  INDEX `fk_turma_periodo1_idx` (`id_periodo` ASC),
  UNIQUE INDEX `turma_unica` (`codigo_componente_turma` ASC, `horario_turma` ASC, `numero_turma` ASC, `id_periodo` ASC),
  INDEX `fk_turma_departamento1_idx` (`id_departamento` ASC),
  CONSTRAINT `fk_turma_tipo1`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `db_cronos`.`perfil_sala_turma` (`id_perfil_sala_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_predio1`
    FOREIGN KEY (`id_predio`)
    REFERENCES `db_cronos`.`predio` (`id_predio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_periodo1`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `db_cronos`.`periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_turma_departamento1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `db_cronos`.`departamento` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 830
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_cronos`.`disponibilidade_sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`disponibilidade_sala` (
  `id_disponibilidade_sala` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `data_reserva` DATE NOT NULL,
  `id_sala` SMALLINT NOT NULL,
  `id_periodo` TINYINT NOT NULL,
  `id_horario_sala` SMALLINT NOT NULL,
  `id_turma` SMALLINT NULL,
  `id_agendamento` MEDIUMINT NULL,
  INDEX `fk_disponibilidade_dia_periodo1_idx` (`id_periodo` ASC),
  INDEX `fk_disponibilidade_dia_sala1_idx` (`id_sala` ASC),
  INDEX `fk_disponibilidade_sala_turma1_idx` (`id_turma` ASC),
  PRIMARY KEY (`id_disponibilidade_sala`),
  UNIQUE INDEX `disponibilidade_unica` (`id_sala` ASC, `data_reserva` ASC, `id_horario_sala` ASC),
  INDEX `fk_disponibilidade_sala_agendamento1_idx` (`id_agendamento` ASC),
  INDEX `fk_disponibilidade_sala_horario1_idx` (`id_horario_sala` ASC),
  CONSTRAINT `fk_disponibilidade_dia_periodo1`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `db_cronos`.`periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disponibilidade_dia_sala1`
    FOREIGN KEY (`id_sala`)
    REFERENCES `db_cronos`.`sala` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disponibilidade_sala_turma1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `db_cronos`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disponibilidade_sala_agendamento1`
    FOREIGN KEY (`id_agendamento`)
    REFERENCES `db_cronos`.`agendamento` (`id_agendamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disponibilidade_sala_horario1`
    FOREIGN KEY (`id_horario_sala`)
    REFERENCES `db_cronos`.`horario` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_cronos`.`feriado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`feriado` (
  `id_feriado` SMALLINT NOT NULL AUTO_INCREMENT,
  `descricao_feriado` VARCHAR(50) NOT NULL,
  `data_feriado` DATE NOT NULL,
  `id_periodo` TINYINT NOT NULL,
  PRIMARY KEY (`id_feriado`),
  INDEX `fk_feriado_periodo1_idx` (`id_periodo` ASC),
  CONSTRAINT `fk_feriado_periodo1`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `db_cronos`.`periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cronos`.`disponibilidade_sala_agendamento_backup`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`disponibilidade_sala_agendamento_backup` (
  `id_disponibilidade_sala` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `data_reserva` DATE NOT NULL,
  `id_sala` SMALLINT NOT NULL,
  `id_periodo` TINYINT NOT NULL,
  `id_horario_sala` SMALLINT NOT NULL,
  `id_turma` SMALLINT NULL,
  `id_agendamento` MEDIUMINT NULL,
  PRIMARY KEY (`id_disponibilidade_sala`),
  INDEX `fk_disponibilidade_sala_backup_sala1_idx` (`id_sala` ASC),
  INDEX `fk_disponibilidade_sala_backup_periodo1_idx` (`id_periodo` ASC),
  INDEX `fk_disponibilidade_sala_backup_horario1_idx` (`id_horario_sala` ASC),
  INDEX `fk_disponibilidade_sala_backup_turma1_idx` (`id_turma` ASC),
  INDEX `fk_disponibilidade_sala_backup_agendamento1_idx` (`id_agendamento` ASC),
  CONSTRAINT `fk_disponibilidade_sala_backup_sala1`
    FOREIGN KEY (`id_sala`)
    REFERENCES `db_cronos`.`sala` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disponibilidade_sala_backup_periodo1`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `db_cronos`.`periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disponibilidade_sala_backup_horario1`
    FOREIGN KEY (`id_horario_sala`)
    REFERENCES `db_cronos`.`horario` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disponibilidade_sala_backup_turma1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `db_cronos`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_disponibilidade_sala_backup_agendamento1`
    FOREIGN KEY (`id_agendamento`)
    REFERENCES `db_cronos`.`agendamento` (`id_agendamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cronos`.`permissao_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`permissao_usuario` (
  `id_papel` TINYINT NOT NULL,
  `id_usuario` SMALLINT NOT NULL,
  PRIMARY KEY (`id_papel`, `id_usuario`),
  INDEX `fk_papel_usuario_has_usuario_usuario1_idx` (`id_usuario` ASC),
  INDEX `fk_papel_usuario_has_usuario_papel_usuario1_idx` (`id_papel` ASC),
  CONSTRAINT `fk_papel_usuario_has_usuario_papel_usuario1`
    FOREIGN KEY (`id_papel`)
    REFERENCES `db_cronos`.`papel_usuario` (`id_papel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_papel_usuario_has_usuario_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db_cronos`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `db_cronos`.`parametros_relatorios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`parametros_relatorios` (
  `id_parametros_relatorios` TINYINT NOT NULL,
  `identificador_parametro_relatorios` VARCHAR(40) NOT NULL,
  `texto_parametro_relatorios` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_parametros_relatorios`),
  UNIQUE INDEX `identificador_unico` (`identificador_parametro_relatorios` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cronos`.`turma_dto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`turma_dto` (
  `id` INT NOT NULL,
  `idTurmaAgrupadora` INT NOT NULL,
  `idUnidade` SMALLINT NOT NULL,
  `cargaHoraria` SMALLINT NOT NULL,
  `capacidadeAluno` SMALLINT NOT NULL,
  `totalSolicitacoes` SMALLINT NOT NULL,
  `qtdMatriculados` SMALLINT NOT NULL,
  `unidade` VARCHAR(100) NOT NULL,
  `codigoComponente` VARCHAR(45) NOT NULL,
  `nomeComponente` VARCHAR(100) NOT NULL,
  `codigo` VARCHAR(45) NOT NULL,
  `descricaoHorario` VARCHAR(100) NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `situacao` VARCHAR(45) NOT NULL,
  `agrupadora` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cronos`.`docente_turma_dto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cronos`.`docente_turma_dto` (
  `id` MEDIUMINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `chDedicada` SMALLINT NOT NULL,
  `idTurma` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_docente_turma_dto_turma_dto1_idx` (`idTurma` ASC),
  CONSTRAINT `fk_docente_turma_dto_turma_dto1`
    FOREIGN KEY (`idTurma`)
    REFERENCES `db_cronos`.`turma_dto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
